apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2drz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2drz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2drz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2drz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2drz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ejfb-tenant/rhtap-demo-app/hacbs-test-project-2drz@sha256:5f9d47fd7ff322565395dc7696fe8b5d4dfc34fd85b6d6566d904f586c039ee3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
